start-at-login = true

after-startup-command = [
  'exec-and-forget sketchybar >> $HOME/.sketchybar/service.log 2>&1',
]

exec-on-workspace-change = [
  '/bin/bash',
  '-c',
  'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE FOCUSED_DISPLAY=$(aerospace list-monitors --focused | awk "{print $1}")',
]

on-focus-changed = [
  'exec-and-forget sketchybar --trigger aerospace_focus_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE',
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = false

[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 20
    inner.vertical =   20
    outer.left =       20
    outer.bottom =     20
    outer.top =        20
    outer.right =      20

[mode.main.binding]

    alt-slash = 'layout tiles horizontal vertical'
    alt-comma = 'layout accordion horizontal vertical'

    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'
    
    alt-ctrl-h = 'join-with left'
    alt-ctrl-j = 'join-with down'
    alt-ctrl-k = 'join-with up'
    alt-ctrl-l = 'join-with right'

    alt-f = 'fullscreen'
    alt-d = 'layout floating tiling'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-t = 'workspace T'

    
    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-t = 'move-node-to-workspace T'
    
   
    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

[[on-window-detected]]
if.app-id = 'com.citrix.receiver.icaviewer.mac'
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = 'com.spotify.client'
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = 'com.openai.chat'
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.kjgfgldnnfoeklkmfkjfagphfepbbdan'
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = 'com.google.Chrome.app.kjbdgfilnfhdoflbpgamdcdgpehopbep'
run = "move-node-to-workspace 3"
